jobs:
- name: show-conjur-secret
  public: true
  plan:
  - task: output-secret
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
      run:
        path: /bin/sh
        args:
        - -c
        - |
          echo "The secret is: $SECRET"
          # echo "The Ops Manager username is: $OPSMAN_USERNAME"
      params:
        SECRET: ((my-conjur-variable))
