resources:
- name: repo
  type: git
  source:
    uri: git@github.com:mjenk664/concourse-example.git
    branch: master
    private_key: ((git-private-key))

jobs:
- name: show-conjur-secret
  plan:
  - get: repo
  - task: output-secret
    file: repo/hello-world/tasks/task.yml
    params:
      SECRET: ((team-secret-variable))
